on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

name: Nightly Build

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Update dependencies
        uses: actions-rs/cargo@v1
        with:
          command: update

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build --all --all-features
